Improved copyable in ReceiveModal
nimiq/wallet pull request #101
Opened 2022-03-04 02:15 UTC by onmax

Changed the `:hover` state in `ReceiveModal`

## Before
![image](https://user-images.githubusercontent.com/22072217/156686032-f05be233-1937-4a81-81a2-c84e0fef20bf.png)

## After
![image](https://user-images.githubusercontent.com/22072217/156686059-b7c071a0-95d9-42fe-86d7-e5b8794f6678.png)

2022-03-07 10:17 UTC, sisou commented
Was there an issue about this? Did designers say this should be changed?

2022-03-07 10:32 UTC, sisou requested changes

2022-03-07 10:32 UTC, sisou commented on src/components/modals/ReceiveModal.vue
> -        }
These styles should be ported, to keep the same hover style.

2022-03-07 10:32 UTC, sisou commented on src/components/modals/ReceiveModal.vue
> -        margin: 1rem 0 4rem;
This border-radius and margins should stay, to keep the same style.

2022-03-08 16:10 UTC, julianbauer commented
@sisou the issue was about the text not turning blue on hover, the background should indeed stay in lightblue

2025-11-15 20:39 UTC, closed without merging