fix: show error when sender is same as recipient
nimiq/wallet pull request #44
Opened 2021-02-20 15:35 UTC by mariofriz

This PR fixes #19 

## Description

When sender and recipient are the same the transaction only fails during transaction step. It should fail early and inform user.

**Steps to reproduce**
- Copy address of current active address
- Open "Send" modal
- Paste address
- No validation happens and amount input is shown

## Changes
- Add recipient validation (sender address different from recipient address)
- Fix small indentation error

## Todo
- [ ] Validate error message
- [ ] Translate error message

2021-02-23 12:14 UTC, sisou requested changes

2021-02-23 12:14 UTC, sisou commented on src/components/modals/SendModal.vue
>                          :maxBytes="64"
Instead of disabling the `message` LabelInput, the whole section should be hidden, just like the `amount-section`.

2021-02-23 12:15 UTC, sisou commented
@Tammoovernice 
This is the wording suggested for this change. Do you agree or would you suggest differently?
![image](https://user-images.githubusercontent.com/1828163/108842175-2be96080-75d9-11eb-9f63-9446dc98f074.png)

2021-02-23 14:14 UTC, Tammoovernice commented
> @Tammoovernice
> This is the wording suggested for this change. Do you agree or would you suggest differently?
> ![image](https://user-images.githubusercontent.com/1828163/108842175-2be96080-75d9-11eb-9f63-9446dc98f074.png)

Let's lose the 'Invalid recipient'. It's tech talk + we can't be sure that the user has the correct recipient but the wrong sender.
I would suggest 'The sender and recipient cannot be identical.' to avoid the more strict 'must'.

2021-02-25 20:41 UTC, mariofriz commented
Can someone please explain the i18n process to me? 

Updated the text and remove message input:
![Screenshot from 2021-02-25 21 38 07](https://user-images.githubusercontent.com/1634484/109214330-ffd50780-77b1-11eb-9ae4-8ab1a66318a2.png)

2021-02-26 11:53 UTC, sisou approved these changes
Regarding i18n: You already extracted the en.po file. After it's merged, we'll push it to Transifex so it can get translated by our translators. Then later, when translated, it will be pulled down in the next deployment.

2021-02-26 11:53 UTC, merged