Center app columns on very large screens
nimiq/wallet pull request #83
Opened 2022-02-14 12:27 UTC by onmax

### Before:
![image](https://user-images.githubusercontent.com/22072217/153864220-bd1b4c4d-28ce-4278-956d-ee757f006c80.png)

### After
![image](https://user-images.githubusercontent.com/22072217/153864252-0535269d-66e6-4eeb-bd3a-56985e0b14f5.png)

2022-02-14 14:22 UTC, sisou commented
Please try navigating to and from the network page, and to and from the settings page. It doesn't look right.

2022-02-14 14:23 UTC, sisou requested changes
This doesn't work for the transition to and from the network and setting views.

2022-02-15 10:18 UTC, onmax commented
I have tried another approach. I'm not a big fan of using fixed distances, but in this case I don't know what other solution we can apply **without changing the DOM**

2022-02-17 10:49 UTC, sisou commented
This still doesn't work when navigating to the network view. I don't think this can be achieved without rethinking the DOM layout.

https://user-images.githubusercontent.com/1828163/154460731-ecfcf37a-4ca3-4813-b6bb-afe3715b3cba.mp4

2022-02-24 15:03 UTC, sisou approved these changes
Amazing, I love it! :heart:

2022-02-24 15:06 UTC, merged