Fix address label flickering on hover
nimiq/wallet pull request #97
Opened 2022-03-02 22:38 UTC by onmax

Solves #95

2022-03-02 22:44 UTC, onmax commented
Not sure how to fix it with the `font-display: swap` as @sisou mentioned: 

https://github.com/nimiq/wallet/issues/95#issuecomment-1057176820

2022-03-07 10:56 UTC, sisou commented
So from your solution here, you think what is going on is that when the user hovers, the CSS `font-weight` is switched to `500`, which makes the browser render a `bold` version of the currently loaded font, until the correct font is loaded and swapped in?

2022-03-07 10:57 UTC, sisou requested changes

2022-03-07 10:57 UTC, sisou commented on public/fonts/fonts.css
> +    font-style: normal, bold;
`font-style` is for italics vs normal, not for bold. Bold is the _weight_ and the keyword `bold` is an alias for `700`, thus only works in the `font-weight` rule.

2022-03-10 15:07 UTC, sisou commented
The current change in this PR leads to the semi-bold (500) font being displayed always, even when not hovered.

2022-03-10 15:38 UTC, closed without merging